# Generated by Django 5.1.1 on 2024-10-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_user_id_recipe_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
    ]
